name: CI
on:
  push:
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Install lua5.1
        run: |
          sudo apt-get update
          sudo apt-get install --yes lua5.1
      - name: mise
        uses: jdx/mise-action@6d1e696aa24c1aa1bcc1adea0212707c71ab78a8 # v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Linters
        run: mise run lint
